# Generated by Django 2.1 on 2018-08-11 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='koreanhotelpriceinfo',
            name='korean_hotel',
        ),
        migrations.RemoveField(
            model_name='koreanhotel',
            name='content',
        ),
        migrations.RemoveField(
            model_name='koreanhotel',
            name='date',
        ),
        migrations.DeleteModel(
            name='KoreanHotelPriceInfo',
        ),
    ]
