# Generated by Django 2.1 on 2018-08-22 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='koreanhotel',
            name='city_name',
        ),
        migrations.AlterField(
            model_name='koreanhoteldetail',
            name='infos',
            field=models.CharField(blank=True, max_length=5000),
        ),
        migrations.AlterField(
            model_name='koreanhoteldetail',
            name='pictures',
            field=models.CharField(blank=True, max_length=5000),
        ),
    ]
