# Generated by Django 2.1 on 2018-08-16 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KoreanHotelDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('pictures', models.CharField(blank=True, max_length=500)),
                ('infos', models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='koreanhotel',
            name='detail_url',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='koreanhoteldetail',
            name='korean_hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotels.KoreanHotel'),
        ),
    ]
