# Generated by Django 2.0.7 on 2018-08-01 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hotel',
        ),
    ]
