# Generated by Django 2.1 on 2018-08-22 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='koreanhotel',
            name='city_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
