# Generated by Django 2.1 on 2018-08-02 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0002_delete_hotel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='koreanhotel',
            name='title',
        ),
        migrations.AddField(
            model_name='koreanhotel',
            name='city',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='koreanhotel',
            name='comments',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='koreanhotel',
            name='country',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='koreanhotel',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='koreanhotel',
            name='price',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='koreanhotel',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='koreanhotel'),
        ),
    ]
