# Generated by Django 2.1 on 2018-08-22 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0002_auto_20180822_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='koreanhoteldetail',
            name='pictures',
            field=models.CharField(blank=True, max_length=50000),
        ),
    ]
