# Generated by Django 2.1 on 2018-08-02 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0003_auto_20180802_1421'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='koreanhotel',
            name='region',
        ),
        migrations.AlterField(
            model_name='koreanhotel',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='region.City'),
        ),
        migrations.AlterField(
            model_name='koreanhotel',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='region.Country'),
        ),
    ]
