# Generated by Django 2.1 on 2018-08-05 02:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlightInfoDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('go_airline', models.CharField(max_length=50)),
                ('go_dep_time', models.CharField(max_length=50)),
                ('go_dep_airport', models.CharField(max_length=50)),
                ('go_flytime', models.CharField(max_length=50)),
                ('go_arr_time', models.CharField(max_length=50)),
                ('go_arr_airport', models.CharField(max_length=50)),
                ('return_airline', models.CharField(max_length=50)),
                ('return_dep_time', models.CharField(max_length=50)),
                ('return_dep_airport', models.CharField(max_length=50)),
                ('return_flytime', models.CharField(max_length=50)),
                ('return_arr_time', models.CharField(max_length=50)),
                ('return_arr_airport', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='flightpriceinfo',
            name='flight',
        ),
        migrations.RemoveField(
            model_name='flightinfo',
            name='date',
        ),
        migrations.AddField(
            model_name='flightinfo',
            name='depart_date',
            field=models.CharField(default='2018-08-24', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flightinfo',
            name='return_date',
            field=models.CharField(default='2018-08-30', max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='FlightPriceInfo',
        ),
        migrations.AddField(
            model_name='flightinfodetail',
            name='flight',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='flights.FlightInfo'),
        ),
    ]
