# Generated by Django 2.1 on 2018-08-08 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_auto_20180805_0240'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flightinfodetail',
            options={'ordering': ['price']},
        ),
    ]
