# Generated by Django 2.1 on 2018-08-08 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0003_auto_20180808_0546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightinfodetail',
            name='url',
            field=models.CharField(blank=True, max_length=800),
        ),
    ]
