# Generated by Django 2.1 on 2018-08-09 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0003_auto_20180806_1846'),
        ('flights', '0003_auto_20180808_0606'),
        ('flights', '0004_auto_20180808_0838'),
    ]

    operations = [
    ]
