# Generated by Django 2.0.7 on 2018-07-31 14:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('hotels', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guide', models.ManyToManyField(related_name='guide_wishlist', to='products.GuideTourInfo')),
                ('korean_hotel', models.ManyToManyField(related_name='korean_hotel_wishlist', to='hotels.KoreanHotel')),
                ('member', models.ManyToManyField(related_name='wishlist_of_member', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ManyToManyField(related_name='ticket_wishlist', to='products.TicketInfo')),
            ],
        ),
    ]
