# Generated by Django 2.1 on 2018-08-13 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='products',
            new_name='product',
        ),
    ]
