# Generated by Django 2.1 on 2018-08-22 12:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('region', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PopularCity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('popular_image', models.CharField(max_length=500)),
                ('popular_city_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tour_name', models.CharField(max_length=255)),
                ('thumbnail', models.CharField(max_length=500)),
                ('title', models.CharField(max_length=255)),
                ('review', models.CharField(max_length=255)),
                ('price', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('meta_info', models.CharField(blank=True, max_length=255)),
                ('no', models.IntegerField(blank=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='region.City')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='region.Country')),
            ],
        ),
        migrations.CreateModel(
            name='ProductDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('region', models.CharField(max_length=20)),
                ('review', models.CharField(max_length=50)),
                ('product_type', models.CharField(blank=True, max_length=10)),
                ('meet_time', models.CharField(blank=True, max_length=10)),
                ('time', models.CharField(blank=True, max_length=10)),
                ('language', models.CharField(blank=True, max_length=10)),
                ('product_type_a', models.CharField(blank=True, max_length=10)),
                ('meet_time_a', models.CharField(blank=True, max_length=10)),
                ('time_a', models.CharField(blank=True, max_length=10)),
                ('language_a', models.CharField(blank=True, max_length=10)),
                ('guide_name', models.CharField(max_length=255)),
                ('guide_desc', models.TextField()),
                ('introduce', models.CharField(max_length=100)),
                ('introduce_desc', models.TextField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='region.City')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='region.Country')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product'),
        ),
    ]
