# Generated by Django 2.0.7 on 2018-08-01 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceInfoBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.IntegerField()),
                ('price', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='guidepriceinfo',
            name='date',
        ),
        migrations.RemoveField(
            model_name='guidepriceinfo',
            name='id',
        ),
        migrations.RemoveField(
            model_name='guidepriceinfo',
            name='price',
        ),
        migrations.RemoveField(
            model_name='ticketpriceinfo',
            name='date',
        ),
        migrations.RemoveField(
            model_name='ticketpriceinfo',
            name='id',
        ),
        migrations.RemoveField(
            model_name='ticketpriceinfo',
            name='price',
        ),
        migrations.CreateModel(
            name='ActivityPriceInfo',
            fields=[
                ('priceinfobase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.PriceInfoBase')),
                ('activity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_price', to='products.ActivityInfo')),
            ],
            bases=('products.priceinfobase',),
        ),
        migrations.AddField(
            model_name='guidepriceinfo',
            name='priceinfobase_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.PriceInfoBase'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticketpriceinfo',
            name='priceinfobase_ptr',
            field=models.OneToOneField(auto_created=True, default='1', on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.PriceInfoBase'),
            preserve_default=False,
        ),
    ]
