# Generated by Django 2.1 on 2018-08-20 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='popularcity',
            name='popular_city_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='popularcity',
            name='popular_image',
            field=models.CharField(max_length=500),
        ),
    ]
