# Generated by Django 2.1 on 2018-08-21 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('review_number', models.CharField(blank=True, max_length=255)),
                ('product_type_icon', models.ImageField(blank=True, upload_to='icon')),
                ('product_type_text', models.CharField(blank=True, max_length=255)),
                ('date', models.IntegerField()),
                ('photo_review', models.ImageField(blank=True, upload_to='review')),
                ('text_review', models.TextField(blank=True)),
                ('guide_name', models.CharField(max_length=255)),
                ('guide_description', models.TextField()),
                ('necessary_guide', models.TextField(blank=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
