# Generated by Django 2.1 on 2018-08-11 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='popularcity',
            name='popular_country_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='popularcity',
            name='popular_city_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='meta_info',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='review',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='thumbnail',
            field=models.ImageField(blank=True, max_length=500, upload_to='product_thumbnail'),
        ),
        migrations.AlterField(
            model_name='product',
            name='tour_name',
            field=models.CharField(max_length=100),
        ),
    ]
