# Generated by Django 2.1 on 2018-08-09 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PopularCityList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('popular_image', models.ImageField(blank=True, upload_to='popular-city-image')),
                ('popular_city_name', models.CharField(max_length=10)),
            ],
        ),
    ]
