# Generated by Django 2.1 on 2018-08-11 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20180811_0934'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='popularcity',
            name='popular_country_name',
        ),
    ]
