# Generated by Django 2.1 on 2018-08-10 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_popularcitylist'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PopularCityList',
            new_name='PopularCity',
        ),
    ]
