# Generated by Django 2.1 on 2018-08-10 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20180810_0606'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productactivitydetail',
            old_name='product_type_text',
            new_name='product_type_text_bold',
        ),
        migrations.RenameField(
            model_name='productguidetourdetail',
            old_name='product_type_text',
            new_name='product_type_text_bold',
        ),
        migrations.RenameField(
            model_name='productticketdetail',
            old_name='product_type_text',
            new_name='product_type_text_bold',
        ),
        migrations.AddField(
            model_name='productactivitydetail',
            name='product_type_text_sm',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='productguidetourdetail',
            name='product_type_text_sm',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='productticketdetail',
            name='product_type_text_sm',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
