# Generated by Django 2.1 on 2018-08-09 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_auto_20180808_0606'),
        ('members', '0002_auto_20180808_0546'),
    ]

    operations = [
    ]
